from fpdf import FPDF
import os
from datetime import datetime

class ReportManager:
    def save_pdf(self, path, data, command="", title="Nmap Scan Report"):

        # Ensure file ends with .pdf
        if not path.lower().endswith(".pdf"):
            path += ".pdf"

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Title
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, title, ln=True, align="C")

        # Date
        pdf.set_font("Arial", "", 12)
        pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
        pdf.ln(10)

        # Command Used
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "Command Used:", ln=True)
        pdf.ln(2)

        # Scan Results
        pdf.set_font("Courier", size=11)
        pdf.multi_cell(0, 6, data)

        # Footer
        pdf.ln(5)
        pdf.set_font("Arial", "I", 10)
        pdf.cell(0, 6, "Generated by Nmap Commander Pro", ln=True, align="L")

        # Create folder if needed
        folder = os.path.dirname(path)
        if folder and not os.path.exists(folder):
            os.makedirs(folder)

        try:
            pdf.output(path)
        except Exception as e:
            print(f"[ERROR] Failed to save PDF: {e}")
            raise e
